{% set name = "libvterm" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.leonerd.org.uk/code/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 09156f43dd2128bd347cbeebe50d9a571d32c64e0cf18d211197946aff7226e0

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake  # [win]
    - make  # [unix]
    - ninja  # [win]
  host:
    - libtool  # [unix]

test:
  commands:
    - test -f $PREFIX/lib/libvterm${SHLIB_EXT}  # [unix]

about:
  home: http://www.leonerd.org.uk/code/libvterm/
  license: MIT
  license_file: LICENSE
  summary: C99 library which implements VT220 or xterm terminal emulator
  dev_url: http://www.leonerd.org.uk/code/libvterm/

extra:
  recipe-maintainers:
    - danielnachun
