{% set name = "libvterm" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.leonerd.org.uk/code/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91eb5088069f4e6edab69e14c4212f6da0192e65695956dc048016a0dab8bcf6

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake  # [win]
    - make  # [unix]
    - ninja  # [win]
  host:
    - libtool  # [unix]

test:
  commands:
    - test -f $PREFIX/lib/libvterm${SHLIB_EXT}  # [unix]

about:
  home: http://www.leonerd.org.uk/code/libvterm/
  license: MIT
  license_file: LICENSE
  summary: C99 library which implements VT220 or xterm terminal emulator
  dev_url: http://www.leonerd.org.uk/code/libvterm/

extra:
  recipe-maintainers:
    - danielnachun
