context:
  version: 0.3.3

package:
  name: libvterm
  version: ${{ version }}

source:
  url: http://www.leonerd.org.uk/code/libvterm/libvterm-${{ version }}.tar.gz
  sha256: 09156f43dd2128bd347cbeebe50d9a571d32c64e0cf18d211197946aff7226e0

build:
  number: 2

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: unix
      then:
        - make
        - perl
    - if: win
      then:
        - cmake
        - ninja
  host:
    - if: unix
      then: libtool
  run_exports:
    - ${{ pin_subpackage('libvterm', upper_bound='x.x') }}

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libvterm${SHLIB_EXT}

about:
  license: MIT
  license_file: LICENSE
  summary: C99 library which implements VT220 or xterm terminal emulator
  homepage: http://www.leonerd.org.uk/code/libvterm/
  repository: http://www.leonerd.org.uk/code/libvterm/

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
